{
 "title": "K8S Deployment Monitoring",
 "tags": [ "availability" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace$\"}, label_app)"
   }
  ]
 },
 "panels": [
  { "title": "$deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deployment" },
  {
   "title": "Cores used / limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace=~\"$namespace$\", pod_name=~\"($deployment)-(.*)\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace$\", pod=~\"($deployment)-(.*)\"})) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\",namespace=~\"$namespace$\", pod_name=~\"($deployment)-(.*)\"}[1m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace$\", pod=~\"($deployment)-(.*)\"})",
     "legendFormat": "Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace$\",unit=\"core\", pod=~\"($deployment)-(.*)\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Deployment Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$namespace$\",pod=~\"($deployment)-(.*)\"})",
     "legendFormat": "Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"^$namespace$\",pod=~\"($deployment)-(.*)\"})",
     "legendFormat": "Limits "
    }
   ]
  },
  {
   "title": "Memory used / limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name!=\"\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"^$namespace$\",pod=~\"($deployment)-(.*)\"})) * 100"
    }
   ]
  },
  {
   "title": "Cores used / requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace=~\"$namespace$\", pod_name=~\"($deployment)-(.*)\"}[1m])) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace$\", pod=~\"($deployment)-(.*)\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory used / requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name!=\"\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"}) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$namespace$\",pod=~\"($deployment)-(.*)\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores / Pod",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\", namespace=~\"$namespace$\", pod_name=~\"($deployment)-(.*)\"}[1m])) by (pod_name, node)",
     "legendFormat": "Used: {{pod_name}} [{{node}}]"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace$\", pod=~\"($deployment)-(.*)\"}) by (container)",
     "legendFormat": "Requests: {{container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"$namespace$\",unit=\"core\", pod=~\"($deployment)-(.*)\"}) by (container)",
     "legendFormat": "Limits: {{container}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory / Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)(.*)\"}) by (pod_name, node)",
     "legendFormat": "Used: {{pod_name}} [{{node}}]"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$namespace$\",pod=~\"($deployment)-(.*)\"}) by (container)",
     "legendFormat": "Requests: {{container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=~\"^$namespace$\",pod=~\"($deployment)-(.*)\"}) by (container)",
     "legendFormat": "Limits: {{container}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace$\", pod=~\"($deployment)-(.*)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage / Pod",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"(.*)($deployment)(.*)\"}) by (persistentvolumeclaim)",
     "legendFormat": "Used {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"(.*)($deployment)(.*)\"}) by (persistentvolumeclaim)",
     "legendFormat": "Limit {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\", container_name!=\"\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"}) by (pod_name)",
     "legendFormat": "Used Pod {{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace$\", container=~\"$deployment\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployment Storage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"(.*)($deployment)(.*)\"})",
     "legendFormat": "Used {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"(.*)($deployment)(.*)\"})",
     "legendFormat": "Limit {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\", container_name!=\"\",namespace=~\"^$namespace$\",pod_name=~\"($deployment)-(.*)\"})",
     "legendFormat": "Used Pod {{pod_name}}"
    }
   ]
  }
 ]
}