apiVersion: v1
kind: Endpoints
metadata:
  name: local-node-exporter
  labels:
      k8s-app: local-node-exporter
subsets:
- addresses:
  - ip: 10.100.102.202
  ports:
  - port: 9100
    protocol: TCP
    name: metrics