apiVersion: v1
kind: Endpoints
metadata:
  name: jenkins-logz-io-prom
  labels:
      k8s-app: jenkins-logz-io-prom
subsets:
- addresses:
  - ip: 172.31.51.243
  ports:
  - port: 80
    protocol: TCP
    name: prometheus