apiVersion: v1
kind: Service
metadata:
    name: jenkins-logz-io-prom
    labels:
        k8s-app: jenkins-logz-io-prom
spec:
    type: ExternalName
    externalName: jenkins.logz.io.prom
    ports:
    - name: prometheus
      port: 80
      protocol: TCP
      targetPort: 80